name: test-app-deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:    
  image-build:
    runs-on: gcr.io/kaniko-project/executor:latest
    steps:
      - run: docker build -t test-app ../../Dockerfile
      - run: docker login -u docker4nitin -p dockertest123
      - run: docker push docker4nitin/test-app 
    
  deploy:
    runs-on: ubuntu-latest
    needs: image-build
    steps:
      - run: ssh root@168.144.66.7 -P PassWord-3478O "docker login -u docker4nitin -p dockertest123;docker pull docker4nitin/test-app;docker run test-app -p 3000:3000"