name: test-app-deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:    
  image-build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install git -y
      - run: git clone -b master https://github.com/NitinRana-code/test-app.git
      - run: cd test-app
      - run: ls
      - run: docker build -t test-app .
      - run: docker login -u docker4nitin -p dockertest123
      - run: docker push docker4nitin/test-app 
    
  deploy:
    runs-on: ubuntu-latest
    needs: image-build
    steps:
      - run: ssh root@168.144.66.7 -P PassWord-3478O
      - run: docker login -u docker4nitin -p dockertest123
      - run: docker pull docker4nitin/test-app
      - run: docker run test-app -p 3000:3000